from .Data import SECONDARY_SCHOOL_ONLINE_LEARNING_REQUIREMENT_TITLE, \
        SECONDARY_SCHOOL_ONLINE_LEARNING_REQUIREMENT_FALSE_TEXT, \
        SECONDARY_SCHOOL_ONLINE_LEARNING_REQUIREMENT_TRUE_TEXT, \
        OST_info, \
        Course